// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uart.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_uart_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_uart_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_uart_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_uart_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_uart_2eproto;
class uart_c;
struct uart_cDefaultTypeInternal;
extern uart_cDefaultTypeInternal _uart_c_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::uart_c* Arena::CreateMaybeMessage<::uart_c>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class uart_c final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:uart_c) */ {
 public:
  inline uart_c() : uart_c(nullptr) {}
  ~uart_c() override;
  explicit PROTOBUF_CONSTEXPR uart_c(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  uart_c(const uart_c& from);
  uart_c(uart_c&& from) noexcept
    : uart_c() {
    *this = ::std::move(from);
  }

  inline uart_c& operator=(const uart_c& from) {
    CopyFrom(from);
    return *this;
  }
  inline uart_c& operator=(uart_c&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const uart_c& default_instance() {
    return *internal_default_instance();
  }
  static inline const uart_c* internal_default_instance() {
    return reinterpret_cast<const uart_c*>(
               &_uart_c_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(uart_c& a, uart_c& b) {
    a.Swap(&b);
  }
  inline void Swap(uart_c* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(uart_c* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  uart_c* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<uart_c>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const uart_c& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const uart_c& from) {
    uart_c::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(uart_c* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "uart_c";
  }
  protected:
  explicit uart_c(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kBaudrateFieldNumber = 2,
    kMaxProcessSizeFieldNumber = 3,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 baudrate = 2;
  void clear_baudrate();
  int32_t baudrate() const;
  void set_baudrate(int32_t value);
  private:
  int32_t _internal_baudrate() const;
  void _internal_set_baudrate(int32_t value);
  public:

  // int32 max_process_size = 3;
  void clear_max_process_size();
  int32_t max_process_size() const;
  void set_max_process_size(int32_t value);
  private:
  int32_t _internal_max_process_size() const;
  void _internal_set_max_process_size(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:uart_c)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int32_t baudrate_;
    int32_t max_process_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_uart_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// uart_c

// string name = 1;
inline void uart_c::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& uart_c::name() const {
  // @@protoc_insertion_point(field_get:uart_c.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void uart_c::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:uart_c.name)
}
inline std::string* uart_c::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:uart_c.name)
  return _s;
}
inline const std::string& uart_c::_internal_name() const {
  return _impl_.name_.Get();
}
inline void uart_c::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* uart_c::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* uart_c::release_name() {
  // @@protoc_insertion_point(field_release:uart_c.name)
  return _impl_.name_.Release();
}
inline void uart_c::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:uart_c.name)
}

// int32 baudrate = 2;
inline void uart_c::clear_baudrate() {
  _impl_.baudrate_ = 0;
}
inline int32_t uart_c::_internal_baudrate() const {
  return _impl_.baudrate_;
}
inline int32_t uart_c::baudrate() const {
  // @@protoc_insertion_point(field_get:uart_c.baudrate)
  return _internal_baudrate();
}
inline void uart_c::_internal_set_baudrate(int32_t value) {
  
  _impl_.baudrate_ = value;
}
inline void uart_c::set_baudrate(int32_t value) {
  _internal_set_baudrate(value);
  // @@protoc_insertion_point(field_set:uart_c.baudrate)
}

// int32 max_process_size = 3;
inline void uart_c::clear_max_process_size() {
  _impl_.max_process_size_ = 0;
}
inline int32_t uart_c::_internal_max_process_size() const {
  return _impl_.max_process_size_;
}
inline int32_t uart_c::max_process_size() const {
  // @@protoc_insertion_point(field_get:uart_c.max_process_size)
  return _internal_max_process_size();
}
inline void uart_c::_internal_set_max_process_size(int32_t value) {
  
  _impl_.max_process_size_ = value;
}
inline void uart_c::set_max_process_size(int32_t value) {
  _internal_set_max_process_size(value);
  // @@protoc_insertion_point(field_set:uart_c.max_process_size)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_uart_2eproto
